apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-d6ye
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-d6ye@sha256:b664d96cebd2738d1742c486b5b98a542b4627c9a56ab379052ab83ecc4dd1fa
        name: my-nodejs
        resources: {}
status: {}
